//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import * as dayjs from 'dayjs';


export interface AppDataViewModel {
    sidebarNavigation?: NavLinkViewModel[] | null;
    item?: Test | null;
}

export interface NavLinkViewModel {
    text: string;
    url: string;
}

export interface Test {
    text?: string | null;
}

export interface SpaceItemViewModel {
    uid: string;
    name?: string | null;
    isChosen: boolean;
    description?: string | null;
}

export enum TestEnum {
    A = 1,
    B = 2,
}